import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/client/index.ts',
    'src/core/index.ts',
    'src/core/ai/index.ts',
    'src/core/auth/index.ts',
    'src/core/auth/client.ts',
    'src/core/auth/schema.ts',
    'src/core/context-store/index.ts',
    'src/core/db/index.ts',
    'src/core/logger/index.ts',
    'src/core/metadata/index.ts',
    'src/core/validators/index.ts',
    'src/constants/index.ts',
    'src/types/index.ts',
    'src/server/index.ts',
    'src/server/middlewares/index.ts',
    'src/utils/index.ts',
    'src/schemas/index.ts',
  ],
  format: ['cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  outDir: 'dist',
  target: 'es2020',
  external: [
    'react',
    'react-dom',
    'next',
    'drizzle-orm',
    'better-auth',
    'ai',
    '@ai-sdk/provider',
    'postgres',
    'zod',
    'date-fns',
    'date-fns-tz',
    'short-uuid',
    'validator',
    'pino',
  ],
})